"""Build a corpus of ground truth plus input variants from a committed spec file.

Spec (JSON): {"pieces": [{"id", "category", "seed", "measures", "language"?}, ...]}
Output per piece: ground_truth.musicxml, score.ly, score.pdf, score.png, scan.png,
photo.png, and a top-level manifest.json describing everything.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal

from lilyscan import __version__
from lilyscan.runtime.config import LILYPOND_VERSION, Settings
from lilyscan.synth.degrade import load_gray, photo, save_png, scan
from lilyscan.synth.engrave import engrave
from lilyscan.synth.generate import PieceSpec, write_ground_truth

log = logging.getLogger(__name__)

Variant = Literal["pdf", "png", "scan", "photo"]
VARIANTS: tuple[Variant, ...] = ("pdf", "png", "scan", "photo")
_FILES: dict[Variant, str] = {
    "pdf": "score.pdf",
    "png": "score.png",
    "scan": "scan.png",
    "photo": "photo.png",
}


@dataclass(frozen=True)
class CorpusItem:
    spec: PieceSpec
    root: Path  # the piece's directory

    @property
    def ground_truth(self) -> Path:
        return self.root / "ground_truth.musicxml"

    def input(self, variant: Variant) -> Path:
        return self.root / _FILES[variant]

    def complete(self) -> bool:
        return self.ground_truth.is_file() and all(self.input(v).is_file() for v in VARIANTS)


def load_spec(path: Path) -> list[PieceSpec]:
    data = json.loads(path.read_text(encoding="utf-8"))
    pieces = [
        PieceSpec(
            id=p["id"],
            category=p["category"],
            seed=int(p["seed"]),
            measures=int(p["measures"]),
            language=p.get("language"),
        )
        for p in data["pieces"]
    ]
    ids = [p.id for p in pieces]
    if len(set(ids)) != len(ids):
        raise ValueError(f"duplicate piece ids in {path}")
    return pieces


def build_corpus(
    spec_path: Path,
    out_dir: Path,
    only: set[str] | None = None,
    force: bool = False,
    settings: Settings | None = None,
) -> list[CorpusItem]:
    s = settings or Settings.from_env()
    items: list[CorpusItem] = []
    for spec in load_spec(spec_path):
        if only and spec.id not in only:
            continue
        item = CorpusItem(spec, out_dir / spec.id)
        items.append(item)
        if item.complete() and not force:
            continue
        log.info("building %s (%s)", spec.id, spec.category)
        generated = write_ground_truth(spec, item.root)
        generated.replace(item.ground_truth)
        engraving = engrave(item.ground_truth, item.root, s)
        clean = load_gray(engraving.png)
        save_png(scan(clean, spec.seed * 10 + 1), item.input("scan"))
        save_png(photo(clean, spec.seed * 10 + 2), item.input("photo"))
    write_manifest(out_dir, spec_path, items)
    return items


def write_manifest(out_dir: Path, spec_path: Path, items: list[CorpusItem]) -> Path:
    manifest: dict[str, Any] = {
        "generator": f"lilyscan {__version__}",
        "lilypond": LILYPOND_VERSION,
        "spec": spec_path.name,
        "license": "Generated by the project (AGPL-3.0-or-later); lyric texts are public domain.",
        "items": [
            {
                **item.spec.to_dict(),
                "ground_truth": item.ground_truth.relative_to(out_dir).as_posix(),
                "inputs": {v: item.input(v).relative_to(out_dir).as_posix() for v in VARIANTS},
            }
            for item in items
        ],
    }
    path = out_dir / "manifest.json"
    out_dir.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return path


def load_corpus(out_dir: Path) -> list[CorpusItem]:
    """Items listed in an already-built corpus's manifest."""
    data = json.loads((out_dir / "manifest.json").read_text(encoding="utf-8"))
    return [
        CorpusItem(
            PieceSpec(
                id=i["id"],
                category=i["category"],
                seed=int(i["seed"]),
                measures=int(i["measures"]),
                language=i.get("language"),
            ),
            out_dir / i["id"],
        )
        for i in data["items"]
    ]
